main:
  - name: "Rescue T&C's"
    url: "/bike-rescue/rescue-sale-terms/"
    weight: 10
legal:
  - name: "Legal Notice"
    url: "/about/legal-notice/"
    weight: 10
  - name: "Cookie Policy"
    url: "/about/cookie-policy/"
    weight: 20
  - name: "Privacy Policy"
    url: "/about/privacy-policy/"
    weight: 30
  - name: "Rescue Terms & Conditions of Sale"
    url: "/bike-rescue/rescue-sale-terms/"
    weight: 40
  - name: "Shuttle Terms & Conditions of Sale"
    url: "/bike-shuttle/shuttle-sale-terms/"
    weight: 50
