main:
  - name: "Rettungs-AGB"
    url: "/fahrrad-rettung/rettungs-verkaufsbedingungen/"
    weight: 10
legal:
  - name: "Rechtlicher Hinweis"
    url: "/about/rechtlicher-hinweis/"
    weight: 10
  - name: "Cookie-Richtlinie"
    url: "/about/cookie-richtlinie/"
    weight: 20
  - name: "Datenschutzerklärung"
    url: "/about/datenschutzerklarung/"
    weight: 30
  - name: "Rettungs-Verkaufsbedingungen"
    url: "/fahrrad-rettung/rettungs-verkaufsbedingungen/"
    weight: 40
  - name: "Shuttle-Verkaufsbedingungen"
    url: "/fahrrad-shuttle/shuttle-verkaufsbedingungen/"
    weight: 50
