main:
  - name: "Rettungs-AGB"
    url: "/bike-rescue/rescue-sale-terms/"
    weight: 10
legal:
  - name: "Rechtlicher Hinweis"
    url: "/about/rechtlicher-hinweis/"
    weight: 10
  - name: "Cookie-Richtlinie"
    url: "/about/cookie-richtlinie/"
    weight: 20
  - name: "Datenschutzerklärung"
    url: "/about/datenschutzerklarung/"
    weight: 30
  - name: "Allg. Verkaufsbedingungen"
    url: "/bike-rescue/rescue-sale-terms/"
    weight: 40
