main:
  - name: "Condiciones del rescate"
    url: "/rescate-bici/terminos-venta-rescate/"
    weight: 10
legal:
  - name: "Aviso legal"
    url: "/about/aviso-legal/"
    weight: 10
  - name: "Política de cookies"
    url: "/about/politica-de-cookies/"
    weight: 20
  - name: "Política de privacidad"
    url: "/about/politica-de-privacidad/"
    weight: 30
  - name: "Condiciones de venta"
    url: "/rescate-bici/terminos-venta-rescate/"
    weight: 40
